server:
  port: 8080

spring:
  kafka:
    producer:
      bootstrap-servers: "192.168.0.108:9092"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
    consumer:
      bootstrap-servers: "192.168.0.108:9092"
      group-id: "spring-boot-kafka-consumer"


topic:
  name: "topic_demo"
